module.exports = [
  //JS & jQuery Libs
  'bower_components/jquery/jquery.min.js',
  'bower_components/jStorage/jstorage.min.js',  
  'bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js',
  'bower_components/fancybox/dist/jquery.fancybox.js',
  'bower_components/smart-app-banner/smart-app-banner.js',
  "bower_components/moment/min/moment.min.js",

  //Angular Libs   
  'bower_components/angular/angular.js',
  'bower_components/cleave.js/dist/cleave-angular.min.js',
  'bower_components/angular-bootstrap/ui-bootstrap.min.js',
  'bower_components/angular-ui-router/release/angular-ui-router.min.js',
  'bower_components/angular-flexslider/angular-flexslider.js',
  'bower_components/angular-translate/angular-translate.js',
  'bower_components/lodash/lodash.js',
  'bower_components/angular-ui-swiper/dist/angular-ui-swiper.js',
  "bower_components/angular-toastr/dist/angular-toastr.js",
  "bower_components/angular-toastr/dist/angular-toastr.tpls.js",
  "frontend/themeassets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js",
  "frontend/themeassets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js",
  "frontend/themeassets/global/plugins/jquery.blockui.min.js",
  "frontend/themeassets/global/plugins/js.cookie.min.js",
  "frontend/themeassets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js",
  "frontend/themeassets/global/plugins/angularjs/angular-touch.min.js",
  "frontend/themeassets/global/plugins/angularjs/plugins/ocLazyLoad.min.js",
  "frontend/themeassets/global/plugins/angularjs/plugins/ui-bootstrap-tpls.min.js",
  "bower_components/oclazyload/dist/ocLazyLoad.min.js",
  
  "frontend/themeassets/global/scripts/app.min.js",
  "frontend/themeassets/layouts/layout/scripts/layout.js",
  "frontend/themeassets/layouts/global/scripts/quick-sidebar.min.js",
  "frontend/themeassets/layouts/global/scripts/quick-nav.min.js",
  "frontend/themeassets/layouts/layout/scripts/demo.min.js",
  "frontend/themeassets/global/plugins/jquery-validation/js/jquery.validate.min.js",
  "frontend/themeassets/global/plugins/backstretch/jquery.backstretch.min.js",
  "frontend/themeassets/pages/scripts/login-4.min.js",

  'frontend/js/app.js',
  'frontend/js/languages/language.js',
  'frontend/js/directives/directive.js',
  'frontend/js/filters/filter.js',
  'frontend/js/services/template.js',
  'frontend/js/factories/navigation.js',
  'frontend/js/factories/api.js',
  'frontend/js/controllers/controller.js',
  'frontend/js/controllers/header-controller.js',
  'frontend/js/controllers/language-controller.js',
  'frontend/js/controllers/BlankController.js',
  'frontend/js/controllers/DashboardController.js',
  'frontend/js/controllers/GeneralPageController.js',
  'frontend/js/controllers/TodoController.js',
  'frontend/js/controllers/UISelectController.js',


  'frontend/js/controllers/appCtrl.js',
  'frontend/js/controllers/dashboardCtrl.js',
  'frontend/js/controllers/customer/customerCtrl.js',
  'frontend/js/controllers/enquiry/createOrEditEnquiryCtrl.js',
  'frontend/js/controllers/enquiry/enquiryCtrl.js',
  'frontend/js/controllers/estimate/createOrEditEstimateCtrl.js',
  'frontend/js/controllers/estimate/estimateCtrl.js',
  'frontend/js/controllers/login/loginCtrl.js',
  'frontend/js/controllers/master/baseMasterCtrl.js',
  'frontend/js/controllers/master/masterAddonCtrl.js',
  'frontend/js/controllers/master/masterExtraCtrl.js',
  'frontend/js/controllers/master/masterMaterialCtrl.js',
  'frontend/js/controllers/master/masterPartCtrl.js',
  'frontend/js/controllers/master/masterProcessCtrl.js',
  'frontend/js/controllers/master/masterShapeCtrl.js',
  'frontend/js/controllers/user/userCtrl.js',
  'frontend/js/controllers/UserProfileController.js',
  

  'frontend/js/services/customer/customerService.js',
  'frontend/js/services/enquiry/createOrEditEnquiryService.js',
  'frontend/js/services/enquiry/enquiryService.js',
  'frontend/js/services/estimate/createOrEditEstimateService.js',
  'frontend/js/services/estimate/estimateService.js',
  'frontend/js/services/login/loginService.js',
  'frontend/js/services/master/baseMatserService.js',
  'frontend/js/services/master/masterAddonService.js',
  'frontend/js/services/master/masterExtraService.js',
  'frontend/js/services/master/masterMaterialService.js',
  'frontend/js/services/master/masterPartService.js',
  'frontend/js/services/master/masterProcessService.js',
  'frontend/js/services/master/masterShapeService.js',
  'frontend/js/services/user/userService.js',
  'frontend/js/services/user/userProfileService.js',
  'frontend/js/services/dashboardService.js'
];